name: flutter_agora_helper
description: A new Flutter package project.
version: 0.0.9

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  agora_chat_sdk: ^1.1.1
  agora_rtc_engine: ^6.2.2
  agora_rtm: ^1.5.8
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.10
  flutter_svg: ^2.0.7
  gap: ^3.0.1
  permission_handler: ^10.4.3
  proximity_screen_lock: ^1.1.0
  proximity_sensor: ^1.3.1

dev_dependencies:
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.5.0+1
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  assets:
    - fonts/
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: DMSans
      fonts:
        - asset: fonts/DMSans-Medium.ttf
          weight: 500
